// Generated by ReScript, PLEASE EDIT WITH CARE


function make(firstName, country) {
  return {
          firstName: firstName,
          country: country
        };
}

function getFirstName(player) {
  return player.firstName;
}

export {
  getFirstName ,
  make ,
}
/* No side effect */
