// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Player from "./Player.bs.js";
import * as Caml_array from "rescript/lib/es6/caml_array.js";
import * as IndexJs from "../index.js";

function log(prim) {
  console.log(prim);
}

console.log("Virat");

var highestScore = [
  "odi",
  264
];

var highestScores = [
  [
    "odi",
    264
  ],
  [
    "test",
    400
  ]
];

console.log(Caml_array.get(highestScores, 0));

function printScore(matchWithScore) {
  var score = matchWithScore[1];
  var match = matchWithScore[0];
  if (match === "odi") {
    var prim = "Highest odi score " + String(score);
    console.log(prim);
    return ;
  }
  if (match === "test") {
    var prim$1 = "Highest test score " + String(score);
    console.log(prim$1);
    return ;
  }
  console.log("Nothing");
}

printScore(highestScore);

printScore([
      "oid",
      264
    ]);

var hsc = [
  /* ODI */0,
  264
];

function printScore$1(matchWithScore) {
  switch (matchWithScore[0]) {
    case /* ODI */0 :
        var prim = "Highest odi score " + String(matchWithScore[1]);
        console.log(prim);
        return ;
    case /* TEST */1 :
        var prim$1 = "Highest test score " + String(matchWithScore[1]);
        console.log(prim$1);
        return ;
    case /* T20I */2 :
        var prim$2 = "Highest t20 score " + String(matchWithScore[1]);
        console.log(prim$2);
        return ;
    
  }
}

printScore$1(hsc);

console.log("Eden Gardens");

var m2 = {
  match2: /* ODI */0,
  staduim: "any"
};

var prim = m2.staduim;

console.log(prim);

var num = 2;

console.log(num);

num = 3;

var prim$1 = Player.getFirstName(Player.make("Rohit", "India"));

console.log(prim$1);

function logString(prim) {
  IndexJs.justPrint(prim);
}

IndexJs.justPrint("Hi");

console.log("Num is " + String(3) + "");

var captain = "Rohit";

var currentSeries = "India tour of WI";

var wicket = /* 'w' */119;

var t20s = 5.4;

var unt;

var highestScores$1 = {
  hd: [
    "odi",
    264
  ],
  tl: {
    hd: [
      "test",
      400
    ],
    tl: /* [] */0
  }
};

var m1 = {
  match: /* ODI */0,
  staduim: "Eden Gardens"
};

var num$1 = 3;

export {
  log ,
  captain ,
  currentSeries ,
  wicket ,
  t20s ,
  unt ,
  highestScore ,
  highestScores$1 as highestScores,
  hsc ,
  printScore$1 as printScore,
  m1 ,
  m2 ,
  logString ,
  num$1 as num,
}
/*  Not a pure module */
